# Generated by Django 3.1.5 on 2021-04-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0004_auto_20210413_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='userName',
            new_name='userID',
        ),
    ]
