# Generated by Django 3.1.5 on 2021-04-14 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookMng', '0005_auto_20210413_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='userID',
        ),
        migrations.AddField(
            model_name='wish',
            name='theUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
