# Generated by Django 3.1.5 on 2021-04-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0007_auto_20210419_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
