# Generated by Django 3.1.5 on 2021-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0008_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_search', models.CharField(max_length=255)),
            ],
        ),
    ]
