# Generated by Django 3.1.5 on 2021-04-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0012_auto_20210420_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
