# Generated by Django 3.1.5 on 2021-04-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0013_auto_20210420_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySearch',
        ),
    ]
