# Generated by Django 3.1.5 on 2021-04-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0014_delete_mysearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSearch',
            fields=[
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
