# Generated by Django 3.1.5 on 2021-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0015_booksearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
