# Generated by Django 3.1.5 on 2021-05-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0019_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
