# Generated by Django 3.1.5 on 2021-05-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0021_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book',
        ),
    ]
