# Generated by Django 3.1.5 on 2021-05-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0022_remove_cart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='seller_book_id',
            field=models.IntegerField(),
        ),
    ]
